language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"

env:
  # - WEBPACK_VERSION=3 HTML_PLUGIN_VERSION=3
  - WEBPACK_VERSION=4 HTML_PLUGIN_VERSION=3
  - WEBPACK_VERSION=4 HTML_PLUGIN_VERSION=4

install: 
  - npm install
  - npm install -D webpack@$WEBPACK_VERSION || true
  - npm install -D html-webpack-plugin@$HTML_PLUGIN_VERSION || true

script: 
  - npm test
  - npm run build

deploy:
  skip_cleanup: true
  on:
    repo: swimmadude66/html-webpack-skip-assets-plugin
    node: "10"
    tags: true
    branch: master
    if: env(WEBPACK_VERSION)=4 AND env(HTML_PLUGIN_VERSION)=4
  provider: npm
  email: "swimmadude66@gmail.com"
  api_key:
    secure: GufE1aXORf6PuzRKBcNpxWhXnfcttsqCQj12R1npVdDF2njc+2FzgYGUAergyh/gkLlWAgcV7DbF1P4qt4jIFRdqXoUtQTI7N1uH7Ay/TdztPxVYancMXoJG/O4e0R2cnfkTCkzRgJF4P3B/WWK5Mq60lLdROrITLsUIwnNI3R88zHNr8u7yjF0RyidpMwTRw9rOyESGQzcPSO4ft4GK/KKmx2+11YXjS2j0OVXcpB4Ee2NCyxXT2REY93EBI0k4ScJFxTkv7Z7sSguJOUJM7EXB/6gAwXx40p5tBNvQ5kmEIaiPscIVcqPdyj4AMGOU/LmDcHxZiZoIvmSLR5/Y2bs0dtKi0hf/SQnvTOccSNJXlJWEGYURUSbOfcTiuUos2lzoqAZnbU8/FujhzQpmKEc0BkNJds1AJCSBkok5QJAmzj3vvs48sJLqcK9z8ydflHOgPaPT0xlkxcEYJqMbK4il1DZXw6sLCKYYRdkAAj2/eKxbMOEetkn74364z7JZdXpP69ryC0AZJH8yCCDca/hd5K/vgxU41feaKJwbpLQocjORlDroctPIxIDU6vRce7Z8i4QtmJFj8P4mGhmWaF9tvJ4o+3LlJOHQYlmlQLUesypRM0savz2glVI8Zon+k3iJbAhFMTpELqw40sj4lgJUaXe9TVvbGP1PflrRPm8=